import { useState, useEffect } from 'react';
import { collection, query, getDocs, where, Timestamp } from 'firebase/firestore';
import { db } from '../../../firebase/config';

export const useCustomerData = () => {
  const [customers, setCustomers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);

  // เปลี่ยน Key เพื่อเคลียร์แคชเก่าที่ไม่มีข้อมูลการเงินทิ้งไป
  const CACHE_KEY = 'dh_customers_data_cache_v6'; 
  const LAST_SYNC_KEY = 'dh_customers_last_sync_v6';
  const staffRoles = ['พนักงานทั่วไป', 'ช่าง', 'พนักงานแพ็ค', 'บัญชี', 'แอดมิน', 'ผู้จัดการ', 'เจ้าของ', 'Admin', 'Manager', 'Owner', 'manager', 'owner', 'admin', 'packer', 'staff'];

  const processCustomerData = (usersData) => {
    const customersOnly = usersData.filter(user => !user.role || !staffRoles.includes(user.role));
    
    // 💎 เรียงลำดับอัจฉริยะ: ดันคนที่ "มีเงินค้างในระบบ (Wallet)" ขึ้นมาก่อนให้แอดมินเห็นง่ายๆ
    customersOnly.sort((a, b) => {
      const salesA = a.stats?.totalSales || 0;
      const salesB = b.stats?.totalSales || 0;
      if (salesB !== salesA) return salesB - salesA; 
      
      const walletA = a.walletBalance || 0;
      const walletB = b.walletBalance || 0;
      return walletB - walletA; 
    });
    setCustomers(customersOnly);
  };

  const fetchCustomers = async (useCache = true) => {
    if (!useCache) setIsRefreshing(true);
    try {
      let cachedUsers = [];
      let lastSync = 0;
      
      if (useCache) {
        const cachedData = localStorage.getItem(CACHE_KEY);
        const syncData = localStorage.getItem(LAST_SYNC_KEY);
        if (cachedData) {
          cachedUsers = JSON.parse(cachedData);
          if (syncData) lastSync = parseInt(syncData, 10);
          
          processCustomerData(cachedUsers);
          setLoading(false);
        }
      }

      if (!useCache || cachedUsers.length === 0) {
        // 🔥 Cleanup ghost accounts generated by previous bugs
        try {
          const { deleteDoc, doc } = await import('firebase/firestore');
          await deleteDoc(doc(db, 'users', '0AUXLNHI'));
          await deleteDoc(doc(db, 'users', '0AUxlnHi'));
        } catch (e) { console.log('Cleanup error (ignored):', e); }
      }

      let q;
      // 🚀 Delta Fetching Optimization
      // ดึงเฉพาะข้อมูลที่เปลี่ยนแปลงนับจากครั้งล่าสุดที่ Sync
      // ลดการอ่าน (Reads) ลงได้อย่างมหาศาลจากหลายพัน Read เหลือแค่หลัก 1-10 Read
      if (useCache && lastSync > 0) {
        q = query(collection(db, 'users'), where('updatedAt', '>', Timestamp.fromMillis(lastSync)));
      } else {
        q = query(collection(db, 'users')); 
      }

      const snapshot = await getDocs(q);
      
      if (!snapshot.empty || !useCache || cachedUsers.length === 0) {
        const fetchedData = snapshot.docs.map(doc => {
          const data = doc.data();
          return {
            id: doc.id,
            ...data,
            // ⚡️ ผนวกข้อมูลทางการเงินและการเสียภาษี ให้พร้อมใช้งานในตาราง
            walletBalance: Number(data.walletBalance || 0),
            creditPoints: Number(data.creditPoints || data.stats?.rewardPoints || 0),
            hasTaxInfo: !!(data.hasTaxInfo || data.taxId || data.taxInfo || data.taxAddress),
            
            createdAt: data.createdAt?.toMillis ? data.createdAt.toMillis() : data.createdAt,
            updatedAt: data.updatedAt?.toMillis ? data.updatedAt.toMillis() : data.updatedAt,
          };
        });

        let updatedUsersData = [];
        if (useCache && lastSync > 0 && cachedUsers.length > 0) {
          // นำข้อมูลที่อัปเดตใหม่มา Merge กับแคชเดิม
          const fetchedMap = new Map(fetchedData.map(u => [u.id, u]));
          updatedUsersData = cachedUsers.map(u => fetchedMap.has(u.id) ? fetchedMap.get(u.id) : u);
          
          // ตรวจสอบและเพิ่มข้อมูลใหม่ที่ยังไม่มีในแคช
          const cachedSet = new Set(cachedUsers.map(u => u.id));
          const newUsers = fetchedData.filter(u => !cachedSet.has(u.id));
          updatedUsersData = [...updatedUsersData, ...newUsers];
        } else {
          updatedUsersData = fetchedData;
        }

        localStorage.setItem(CACHE_KEY, JSON.stringify(updatedUsersData));
        localStorage.setItem(LAST_SYNC_KEY, Date.now().toString());
        processCustomerData(updatedUsersData);
      } else if (cachedUsers.length > 0) {
        // หากไม่มีข้อมูลอัปเดตใหม่ ให้ใช้แคชต่อไป และขยับเวลา Sync
        localStorage.setItem(LAST_SYNC_KEY, Date.now().toString());
      }
    } catch (error) {
      console.error("Error fetching customers:", error);
    } finally {
      setLoading(false);
      setIsRefreshing(false);
    }
  };

  useEffect(() => {
    fetchCustomers(true);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return { customers, setCustomers, loading, isRefreshing, fetchCustomers, CACHE_KEY };
};